---
# example.com es un dominio recomendado para documentación por la Autoridad de
# Números Asignados de Internet (IANA)
git_config:
  core:
    autocrlf = input

  push:
    default: current

  user:
    email: mi.nombre@example.com
    name: Mi Nombre
