---
# example.com es un dominio recomendado para documentación por la Autoridad de
# Números de Internet Asignados (IANA)
git_config:
  push:
    default: current

  user:
    email: mi.nombre@example.com
    name: Mi Nombre
