### REQUERIDO
# El espacio de nombre de la colección en el que vive todo el contenido. Solo puede contener caracteres alfanuméricos
# en minúscula y guion bajo. El espacio de nombre no puede comenzar con guion bajo ni números y no puede tener guiones
# bajos consecutivos.
namespace: byque

# El nombre de la colección. Tiene las mismas restricciones que el espacio de nombre.
name: local

# La versión de la colección. Debe ser compatible con versionamiento semántico.
version: 0.0.3

# La ruta al léeme en archivo Markdown (.md). Esta ruta es relativa a la raíz de la colección.
# El nombre del archivo se mantiene en inglés para su correcta visualización en GitHub.
readme: README.md

# Lista de los autores del contenido de la colección. Puede ser solo el nombre o en el formato
# 'Nombre Completo <email> (url)
# @nicks:irc/im.site#channel'
authors:
- Byron Quezada


### OPCIONAL pero fuertemente sugerido
# Un resumen breve con la descripción de la colección
description: Configuración de la computadora personal de @byque

# Una licencia singular o una lista de licencias para el contenido dentro de la colección. Ansible Galaxy actualmente
# solo acepta licencias L(SPDX,https://spdx.org/licenses/). Este valor es mutuamente excluyente con 'licence_file'.
license:
- GPL-3.0

# Una lista de etiquetas para asociar con la colección para indexamiento/búsqueda. El nombre de la etiqueta tiene los
# mismos requerimientos que el nombre de espacios y el nombre de la colección.
tags:
  - debian

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}

# La URL del repositorio SCM del que se origina
repository: https://github.com/byque/ansible-coleccion-local

# The URL to any online docs
documentation: http://docs.example.com

# The URL to the homepage of the collection/project
homepage: http://example.com

# La URL de la página de seguimiento de problemas
issues: https://github.com/byque/ansible-coleccion-local/issues

# Una lista de patrones de archivo tipo glob usados para filtrar cualquier archivo o directorio que no se debería
# incluir en el artefacto construído. Un patrón coincide con la ruta relativa del archivo o directorio con respecto al
# directorio de la colección. Esto usa 'fnmatch' para emparejar los archivos o directorios. Algunos directorios y
# archivos como 'galaxy.yml', '*.pyc', '*.retry' y '.git' siempre están filtrados. Mutuamente excluyente con 'manifest'
build_ignore:
- .idea
- .venv

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null
