---
- name: "La tarea está ejecutándose desde el rol"
  ansible.builtin.debug:
    msg: "Esta es una tarea de Git."

- name: Instalar Git desde Advanced Package Tool
  become: yes
  ansible.builtin.apt:
    name: git
    state: present

- name: Generar la configuración de Git
  ansible.builtin.template:
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    src: gitconfig.j2
