---
name: Integración Contínua

on: [push]

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    steps:
      - name: Chequear el código
        uses: actions/checkout@v4

      - run: python --version
